"""Offline price backend: reads the bundled synthetic demo series.

The snapshot files under ``data/snapshots/prices/`` carry **synthetic** daily
series (generated by ``scripts/build_price_snapshots.py`` with fixed seeds and
plausible base levels). They are labelled ``synthetic: true`` so nothing in
the pipeline can mistake them for real market data; the report footer says
which channel each figure came from.

Offsets are stored as ``days_ago`` and rebased onto the current date at load
time, keeping trend windows meaningful whenever the demo runs.
"""

from __future__ import annotations

import json
from datetime import date, timedelta
from pathlib import Path

from pydantic import BaseModel, Field

from mining_brief_core import paths
from mining_brief_core.errors import DataNotFoundError, ProviderError

from .base import ProviderOutcome
from ..commodities import CommoditySpec
from ..models import PricePoint


class SnapshotPoint(BaseModel):
    days_ago: int
    price: float


class PriceSnapshot(BaseModel):
    schema_: str = Field(alias="schema")
    commodity: str
    unit: str
    synthetic: bool = True
    note: str = ""
    points: list[SnapshotPoint]

    model_config = {"populate_by_name": True}


class SnapshotPriceProvider:
    """Quote/series backend over ``data/snapshots/prices/*.json``."""

    def __init__(self, snapshot_dir: Path | None = None) -> None:
        self._dir = snapshot_dir or paths.prices_snapshot_dir()
        self._cache: dict[str, PriceSnapshot] = {}

    def _load(self, spec: CommoditySpec) -> PriceSnapshot:
        if spec.key not in self._cache:
            path = self._dir / spec.snapshot_file
            if not path.is_file():
                raise ProviderError(f"price snapshot not found: {path}")
            raw = json.loads(path.read_text(encoding="utf-8"))
            self._cache[spec.key] = PriceSnapshot.model_validate(raw)
        return self._cache[spec.key]

    def _as_points(self, spec: CommoditySpec, snapshot: PriceSnapshot) -> list[PricePoint]:
        today = date.today()
        points = [
            PricePoint(
                commodity=spec.key,
                date=today - timedelta(days=point.days_ago),
                price=point.price,
                unit=snapshot.unit,
            )
            for point in snapshot.points
        ]
        points.sort(key=lambda p: p.date)
        return points

    def get_quote(self, spec: CommoditySpec, on: date | None) -> tuple[PricePoint, ProviderOutcome]:
        snapshot = self._load(spec)
        points = self._as_points(spec, snapshot)
        if not points:
            raise ProviderError(f"snapshot for {spec.key} contains no points")
        if on is None:
            return points[-1], self._outcome(snapshot)
        for point in reversed(points):
            if point.date == on:
                return point, self._outcome(snapshot)
        earliest, latest = points[0].date, points[-1].date
        raise DataNotFoundError(
            f"no snapshot point for {spec.key} on {on.isoformat()} "
            f"(available {earliest.isoformat()}..{latest.isoformat()})"
        )

    def get_series(self, spec: CommoditySpec, days: int) -> tuple[list[PricePoint], ProviderOutcome]:
        snapshot = self._load(spec)
        cutoff = date.today() - timedelta(days=days)
        points = [p for p in self._as_points(spec, snapshot) if p.date >= cutoff]
        if not points:
            raise ProviderError(f"no snapshot points for {spec.key} within {days} days")
        return points, self._outcome(snapshot)

    def _outcome(self, snapshot: PriceSnapshot) -> ProviderOutcome:
        return ProviderOutcome(
            mode="snapshot",
            notes=[
                "offline synthetic demo series (not real market data); see docs/data-sources.md"
            ],
        )
