"""Generate the synthetic offline price series bundled in ``data/snapshots/prices``.

These series are **demo data**: fixed-seed random walks around plausible base
levels, labelled ``synthetic: true`` in every emitted file and documented in
``docs/data-sources.md``. The point is that the whole agent pipeline runs
deterministically offline; the live channel (Sina quotes) is the only source
of real market figures.

Run: ``python scripts/build_price_snapshots.py``
"""

from __future__ import annotations

import json
import random
from dataclasses import dataclass
from pathlib import Path

from lme_price_mcp.commodities import COMMODITIES
from mining_brief_core.paths import prices_snapshot_dir

DAYS = 90
SCHEMA = "mining-brief-agent/price-snapshot@1"


@dataclass(frozen=True)
class SeriesParams:
    base: float
    drift_pct_over_window: float
    daily_volatility: float
    seed: int
    decimals: int


# Keys must cover every commodity in the registry.
PARAMS: dict[str, SeriesParams] = {
    "copper": SeriesParams(
        base=9_500.0, drift_pct_over_window=2.0, daily_volatility=0.010, seed=101, decimals=1
    ),
    "zinc": SeriesParams(
        base=2_700.0, drift_pct_over_window=-3.0, daily_volatility=0.013, seed=102, decimals=1
    ),
    "nickel": SeriesParams(
        base=15_500.0, drift_pct_over_window=-6.0, daily_volatility=0.016, seed=103, decimals=1
    ),
    "lithium_carbonate": SeriesParams(
        base=76_000.0, drift_pct_over_window=-8.0, daily_volatility=0.018, seed=104, decimals=0
    ),
    "iron_ore": SeriesParams(
        base=780.0, drift_pct_over_window=1.0, daily_volatility=0.012, seed=105, decimals=1
    ),
}


def generate_series(params: SeriesParams, days: int = DAYS) -> list[float]:
    """Deterministic random walk with a small constant drift."""
    rng = random.Random(params.seed)
    daily_drift = params.drift_pct_over_window / 100.0 / days
    price = params.base
    series: list[float] = []
    for _ in range(days):
        price *= 1.0 + daily_drift + rng.gauss(0.0, params.daily_volatility)
        series.append(round(price, params.decimals))
    return series


def build_snapshot(spec_key: str, params: SeriesParams, days: int = DAYS) -> dict:
    spec = COMMODITIES[spec_key]
    prices = generate_series(params, days)
    return {
        "schema": SCHEMA,
        "commodity": spec.key,
        "unit": spec.unit,
        "synthetic": True,
        "note": (
            "SYNTHETIC demo series generated by scripts/build_price_snapshots.py "
            f"(seed={params.seed}); NOT real market data. Offsets are days_ago, "
            "rebased onto the current date at load time."
        ),
        "generator": "scripts/build_price_snapshots.py",
        "points": [
            {"days_ago": days - 1 - index, "price": price} for index, price in enumerate(prices)
        ],
    }


def main() -> None:
    dest = prices_snapshot_dir()
    dest.mkdir(parents=True, exist_ok=True)
    missing = set(COMMODITIES) - set(PARAMS)
    if missing:
        raise SystemExit(f"PARAMS missing entries for: {sorted(missing)}")
    for key, params in PARAMS.items():
        spec = COMMODITIES[key]
        payload = build_snapshot(key, params)
        target: Path = dest / spec.snapshot_file
        with target.open("w", encoding="utf-8", newline="\n") as handle:
            handle.write(json.dumps(payload, ensure_ascii=False, indent=2) + "\n")
        print(f"{key}: {len(payload['points'])} points -> {target}")


if __name__ == "__main__":
    main()
